import { Application } from "express";
import authRoutes from "./routes/auth.routes";
import qrRoutes from "./routes/qr.routes";
import orgRoutes from "./routes/organization.routes";
import branchRoutes from "./routes/branch.routes";
import menuRoutes from "./routes/menu.routes";
import tableRoutes from "./routes/table.routes";
import userRoutes from "./routes/user.routes";
import roleRoutes from "./routes/role.routes";
import employeeRoutes from "./routes/employee.routes";
import orderRoutes from "./routes/order.routes";
import billRoutes from "./routes/bill.routes";
import kitchenRoutes from "./routes/kitchen.routes";
import reservationRoutes from "./routes/reservation.routes";
import customerRoutes from "./routes/customer.routes";
import attendanceRoutes from "./routes/attendance.routes";
import inventoryRoutes from "./routes/inventory.routes";
import supplierRoutes from "./routes/supplier.routes";
import recipeRoutes from "./routes/recipe.routes";
import analyticsRoutes from "./routes/analytics.routes";
import uploadRoutes from "./routes/upload.routes";

export default (app: Application) => {
  app.use("/api/v1/auth", authRoutes);
  app.use("/api/v1/qr", qrRoutes);
  app.use("/api/v1/organization", orgRoutes);
  app.use("/api/v1/branch", branchRoutes);
  app.use("/api/v1/menu", menuRoutes);
  app.use("/api/v1/table", tableRoutes);
  app.use("/api/v1/user", userRoutes);
  app.use("/api/v1/role", roleRoutes);
  app.use("/api/v1/employee", employeeRoutes);
  app.use("/api/v1/order", orderRoutes);
  app.use("/api/v1/bill", billRoutes);
  app.use("/api/v1/kitchen", kitchenRoutes);
  app.use("/api/v1/reservation", reservationRoutes);
  app.use("/api/v1/customer", customerRoutes);
  app.use("/api/v1/attendance", attendanceRoutes);
  app.use("/api/v1/inventory", inventoryRoutes);
  app.use("/api/v1/supplier", supplierRoutes);
  app.use("/api/v1/recipe", recipeRoutes);
  app.use("/api/v1/analytics", analyticsRoutes);
  app.use("/api/v1/upload", uploadRoutes);
};
